# Generated by Django 3.2.5 on 2022-05-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Форма Родителя(опекуна) №1',
            },
        ),
    ]
