# Generated by Django 3.2.5 on 2022-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50)),
                ('user_agreement', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Список родителя №2',
                'verbose_name_plural': 'Список родителей(опекунов) №2',
            },
        ),
        migrations.AlterModelOptions(
            name='parent1',
            options={'verbose_name': 'Список родителя №1', 'verbose_name_plural': 'Список родителей(опекунов) №1'},
        ),
        migrations.AddField(
            model_name='parent1',
            name='user_agreement',
            field=models.BooleanField(default=True),
        ),
    ]
