# Generated by Django 3.2.5 on 2022-05-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220516_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='AKDS',
            field=models.DateField(null=True, verbose_name='Дата прививки АКДС'),
        ),
        migrations.AddField(
            model_name='kid',
            name='BSZH',
            field=models.DateField(null=True, verbose_name='Дата прививки БЦЖ'),
        ),
        migrations.AddField(
            model_name='kid',
            name='copyVaccSertificate',
            field=models.ImageField(null=True, upload_to='VaccSertificate/', verbose_name='Копия сертификата о прививках'),
        ),
        migrations.AddField(
            model_name='kid',
            name='poliomielit',
            field=models.DateField(null=True, verbose_name='Дата прививки от полиомиелита'),
        ),
        migrations.AddField(
            model_name='kid',
            name='polis',
            field=models.CharField(max_length=20, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='kid',
            name='snils',
            field=models.CharField(max_length=20, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='birthDate',
            field=models.DateField(null=True, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='copyPassport',
            field=models.ImageField(null=True, upload_to='passports/', verbose_name='Копия паспорта'),
        ),
        migrations.AlterField(
            model_name='parent1',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent1',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='parent1',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='parent1',
            name='status',
            field=models.CharField(max_length=10, null=True, verbose_name='Статус'),
        ),
    ]
