# Generated by Django 3.2.5 on 2022-05-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220517_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='medExit',
            field=models.BooleanField(default=False, verbose_name='Имеется медотвод'),
        ),
        migrations.AddField(
            model_name='kid',
            name='refusal_vaccinations',
            field=models.BooleanField(default=False, verbose_name='Отказ от прививок'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='polis',
            field=models.CharField(max_length=20, null=True, verbose_name='Полис'),
        ),
    ]
